import = [
	# "C:\\Users\\Raksmey\\AppData\\Roaming\\alacritty\\themes\\github-dark-tritanopia.toml",
		# "C:\\Users\\Raksmey\\AppData\\Roaming\\alacritty\\themes\\baitong.toml",
			 "C:\\Users\\Raksmey\\AppData\\Roaming\\alacritty\\themes\\nightfly.toml",
	# 	"C:\\Users\\Joe\\AppData\\Roaming\\alacritty\\themes\\baitong.toml",
	# "C:\\Users\\Joe\\AppData\\Roaming\\alacritty\\themes\\catppuccin-macchiato.toml",
		# "C:\\Users\\Joe\\AppData\\Roaming\\alacritty\\themes\\nightfly.toml",
]

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "CaskaydiaCove Nerd Font"
bold.family = "CaskaydiaCove Nerd Font"
italic.family = "CaskaydiaCove Nerd Font"
bold_italic.family = "CaskaydiaCove Nerd Font"
offset = {x = 0, y = 5}

size = 12

[shell]

# args = ["--cd ~"]
program = 'ubuntu2004.exe'

